### ISSUE TITLE
Position calculation bugs with relative layouts

### ISSUE THREAD

**Issue by saibotk** [Vuepic/vue3-date-time-picker#8]
**Describe the bug**
The menu has an incorrect position, when using any relative layout in a parent element.
This is due to the use of `offsetTop` which is then the offset to its relative parent instead of the viewport. 

**To Reproduce**
1. Put the component within a container that has a relative CSS layout.
2. Open the menu
3. See the wrong positioning

**Expected behavior**
The position should be correct even within relative layouts, which is commonly used and needed in certain situations. 
The position calculation could be fixed with some approaches like they are presented here: https://stackoverflow.com/questions/442404/retrieve-the-position-x-y-of-an-html-element#11396681

**Screenshots**
![image](https://user-images.githubusercontent.com/10776964/134817820-3d672c4d-690e-43e2-ae13-04715335884a.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 92

**Comment by Jasenkoo** [comment]
WIll be fixed in the next version

**Comment by saibotk** [comment]
Wow that was fast, thank you very very much and thank you for your work on this project <3

**Comment by Jasenkoo** [comment]
Fixed, had to use some more precise positioning since there were some different offsets on different layouts.

New version [v2.1.2](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.1.2)

Glad you like the component.

**Comment by saibotk** [comment]
Sadly, this still did not fix my issue. :(

![image](https://user-images.githubusercontent.com/10776964/136677696-aa415c44-3084-4a2a-a03a-2e7b401de490.png)

There is nothing really special about my environment except, that this input element is inside two relative divs (over the course of the entire tree) and those seem to break it. Its calculated top value is also only 48 which is the height of the object only.

If you need more info just ask :)

**Comment by Jasenkoo** [comment]
Can you try downgrading to version `2.1.6` and tell me if you still have the issue?

**Comment by saibotk** [comment]
Mhh this JS / CSS interaction is really weird :D 

Thank you very very much for the fast response and help!

**Comment by Jasenkoo** [comment]
No problem :)

**Comment by saibotk** [comment]
Just Tailwindcss nothing special about my setup, if really needed, I might find some time to put some code up.
